config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cans#index'
  resources :cans do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'set_search'
    end
  end

  resources :users, only: :show do
    resource :relationship, only: [:create, :destroy]
    resources :followings, only: :index
    resources :followers, only: :index
  end
end

app/models/active.rb
class Active < ActiveHash::Base

  self.data = [
    {id: 0, name: '---'},
    {id: 1, name: '読書'}, 
    {id: 2, name: '筋トレ'}, 
    {id: 3, name: 'ランニング'}, 
    {id: 4, name: 'ウォーキング'}, 
    {id: 5, name: 'プログラミング'}, 
    {id: 6, name: '英会話'}, 
    {id: 7, name: '勉強'}, 
    {id: 8, name: '瞑想'}, 
    {id: 9, name: '掃除'}, 
    {id: 10, name: 'その他'}
]

  include ActiveHash::Associations
  has_many :cans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/can.rb
class Can < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :active
  belongs_to_active_hash :place
  belongs_to_active_hash :set_time

  with_options numericality: { other_than: 0 } do
    validates :active_id
    validates :place_id
    validates :set_time_id
  end

  validates :image, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy   #外部キーを持つデータのdestroyを行うための設定
  has_many :likes, dependent: :destroy
  has_one_attached :image

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :user
  belongs_to :can
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :can

  validates_uniqueness_of :can_id, scope: :user_id
end

app/models/place.rb
class Place < ActiveHash::Base

  self.data = [
    {id: 0, name: '---'},
    {id: 1, name: '自宅'}, 
    {id: 2, name: '公園'}, 
    {id: 3, name: 'ジム'}, 
    {id: 4, name: '職場'}, 
    {id: 5, name: '教室'}, 
    {id: 6, name: 'カフェ'}, 
    {id: 7, name: '図書館'}, 
    {id: 8, name: '屋外'}, 
    {id: 9, name: 'その他'} 
]

  include ActiveHash::Associations
  has_many :cans
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/set_time.rb
class SetTime < ActiveHash::Base

  self.data = [
    {id: 0, name: '---'},
    {id: 1, name: '15分'}, 
    {id: 2, name: '30分'}, 
    {id: 3, name: '45分'}, 
    {id: 4, name: '1時間00分'}, 
    {id: 5, name: '1時間15分'}, 
    {id: 6, name: '1時間30分'}, 
    {id: 7, name: '1時間45分'}, 
    {id: 8, name: '2時間00分'}, 
    {id: 9, name: '2時間15分'},
    {id: 10, name: '2時間30分'},
    {id: 11, name: '2時間45分'},
    {id: 12, name: '3時間00分'},
    {id: 13, name: '3時間以上'} 
]

  include ActiveHash::Associations
  has_many :cans
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cans, dependent: :destroy   #外部キーを持つデータのdestroyを行うための設定
  has_many :comments, dependent: :destroy   #外部キーを持つデータのdestroyを行うための設定
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user

  
  validates :nickname, presence: true, length: { maximum: 6 }

  def already_liked?(can)
    self.likes.exists?(can_id: can.id)
  end

  
end

app/controllers/cans_controller.rb
class CansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :set_search]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_search, only: [:index, :set_search]

  def index
    @cans = Can.all.order("created_at DESC")
  end

  def new
    @can = Can.new
  end

  def create
    @can = Can.new(can_params)
    if @can.valid?
      @can.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    # @can = Can.find(params[:id])
    @comment = Comment.new
    @comments = @can.comments.includes(:user)
  end

  def edit
    # @can = Can.find(params[:id])
  end

  def update
    # @can = Can.find(params[:id])
    @can.update(can_params)
    if @can.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    # @can = Can.find(params[:id])
    @can.destroy
    redirect_to root_path
  end

  def set_search
    @search = Can.ransack(params[:q])
    @cans = @search.result
  end

  private

  def set_item
    @can = Can.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && @current_user.id == @can.user_id
      redirect_to action: :index
    end
  end

  def can_params
    params.require(:can).permit(:active_id, :place_id, :set_time_id, :description, :image).merge(user_id: current_user.id)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to can_path(@comment.can)
    else
      @can = @comment.can
      @comments = @can.comments
      render "cans/show"  # views/cans/show.html.erbのファイルを参照
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, can_id: params[:can_id])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = User.find(params[:user_id]).followers
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @followings = User.find(params[:user_id]).followings
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(can_id: params[:can_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @can = Can.find(params[:can_id])
    @like = current_user.likes.find_by(can_id: @can.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @cans = @user.cans
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cans_helper.rb
module CansHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cans/edit.html.erb
<%= form_with model: @can, url: can_path, method: :patch, local: true do |f| %>
    
    <div class="can-box">
    <h2 class="can-plan">編集しよう！！</h2>
      何を？
      <%= f.collection_select(:active_id, Active.all, :id, :name, {}, {class:"active-select"}) %>
      どこで？
      <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"place-select"}) %>
      何分？
      <%= f.collection_select(:set_time_id, SetTime.all, :id, :name, {}, {class:"set_time-select"}) %>
      メモ書き
      <%= f.text_area :description, class:"description", placeholder:"メモ" %>

      <%= f.label :image, "画像アップロード", class: "image_btn" %> 
      <%= f.file_field :image, class:"image_form" %> 

      <%= f.submit "編集する", class:"btn" %>

    </div>

<% end %>

app/views/cans/index.html.erb
<% if user_signed_in? %>
  <div class="greeting">
    ユーザー名:
    <%= link_to "#{current_user.nickname}", user_path(current_user), class: :greeting_link %>さん
  </div>
<% end %>

<%# ログイン時のエラーメッセージ  %>
    <div class='login-flash-message'>
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    </div>

<%# 検索機能表示 shared/_search.html.erb %>
<%= render "shared/search" %>

<%# 投稿表示 shared/_can.html.erb %>
<%= render "shared/can" %>

app/views/cans/new.html.erb
<%= form_with model: @can, url: cans_path, method: :post, local: true do |f| %>
    
    <%= render 'shared/error_message', model: f.object %>
    
    <div class="can-box">
    <h2 class="can-plan">今日できたこと！！</h2>
      何を？
      <%= f.collection_select(:active_id, Active.all, :id, :name, {}, {class:"active-select"}) %>
      どこで？
      <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"place-select"}) %>
      何分？
      <%= f.collection_select(:set_time_id, SetTime.all, :id, :name, {}, {class:"set_time-select"}) %>
      メモ書き
      <%= f.text_area :description, class:"description", placeholder:"メモ" %>

      <%= f.label :image, "画像アップロード", class: "image_btn" %>
      <%= f.file_field :image, class:"image_form" %>

      <%= f.submit "投稿する", class:"btn" %>

    </div>
    
<% end %>

app/views/cans/set_search.html.erb
<% if user_signed_in? %>
  <div class="greeting">
    ユーザー名:
    <%= link_to "#{current_user.nickname}", user_path(current_user), class: :greeting_link %>さん
  </div>
<% end %>

<%# 投稿表示 shared/_can.html.erb %>
<%= render "shared/can" %>

app/views/cans/show.html.erb
<div class="main">
  <div class="detail-main">

      <% if user_signed_in? && current_user.id == @can.user_id %>
        <div class="can-edit-delete">
          <%= link_to "編集", edit_can_path(@can.id), class: :can_edit %>
          <%= link_to "削除", can_path(@can.id), class: :can_delete, method: :delete %>
        </div>
      <% end %>

        <tr>
          <th class="detail-can"></th>
          <td class="detail-value"><%= image_tag @can.image, class: :can_image if @can.image.attached? %></td>
        </tr>
        
    <table class="detail-table">
      <tbody>
        
        <tr>
          <th class="detail-can">投稿者</th>
          <td class="detail-value"><%= @can.user.nickname %></td>
        </tr>

        <tr>
          <th class="detail-can">何を</th>
          <td class="detail-value"><%= @can.active.name %></td>
        </tr>

        <tr>
          <th class="detail-can">場所</th>
          <td class="detail-value"><%= @can.place.name %></td>
        </tr>

        <tr>
          <th class="detail-can">時間</th>
          <td class="detail-value"><%= @can.set_time.name %></td>
        </tr>

        <tr>
          <th class="detail-can">メモ</th>
          <td class="detail-value"><%= @can.description %></td>
        </tr>

        <tr>
          <th class="detail-can">投稿日時</th>
          <td class="detail-value"><%= l @can.created_at, format: :short %></td>
        </tr>
      </tbody>
    </table>
    <% if current_user %>
      <% if current_user.already_liked?(@can) %>
        <%= link_to can_likes_path(@can), method: :delete do %>
        <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to can_likes_path(@can), method: :post do %>
        <i class="far fa-heart"></i>
        <% end %>
      <% end %>
    <% end %>
    <%= @can.likes.count %>
  </div>

  <div class="comments">
    <% if user_signed_in? %>
      <%= form_with model: [@can, @comment], local: true do |f| %>
        <%= f.text_area :text, class:"text", placeholder: "コメント欄" %><br>
        <%= f.submit "送信", class:"comment-btn"%>
      <% end %>
    <% else %>
      <p>※コメントを投稿する場合ログインが必要です!※</p>
    <% end %>
    
    <div class="comments-list">
    <h3>コメント一覧</h3>
      <% @comments.each do |comment| %>
        🟢<%= comment.text %>
        <p><%= comment.user.nickname %>さん</p><br>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main-top">
  <div class="main-follow">
    <% if user_signed_in? && current_user != @user %>
      <% if current_user.active_relationships.exists?(target_user_id: @user.id) %>
        <%= link_to 'フォロー解除', [@user, :relationship], method: :delete %>
      <% else %>
        <%= link_to 'フォローする', [@user, :relationship], method: :post %>
      <% end %>
    <% end %>

    <div>
      <%= link_to 'フォロー',  [@user, :followings] %>
      <%= @user.followings.count %>
    </div>
    <div>
      <%= link_to 'フォロワー',  [@user, :followers] %>
      <%= @user.followers.count %>
    </div>
  </div>

  <p><%= @nickname %>さんの投稿一覧</p>
  <% @cans.each do |can| %>
    <div class="can">
      <%= link_to image_tag(can.image, class: :can_img) if can.image.attached? %>
      <div class="can_name">
          <%= can.user.nickname %>さん
          <div class="can_active">
            -<%= can.active.name %>-
          </div>
     </div>
     <% if current_user.already_liked?(can) %>
      <%= link_to can_likes_path(can), method: :delete do %>
      <i class="fas fa-heart"></i>
      <% end %>
    <% else %>
      <%= link_to can_likes_path(can), method: :post do %>
      <i class="far fa-heart"></i>
      <% end %>
    <% end %>
    <%= can.likes.count %>
  <% end %>
</div>