config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cans#index'
  resources :cans do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'set_search'
    end
  end

  resources :users, only: :show do
    resource :relationship, only: [:create, :destroy]
    resources :followings, only: :index
    resources :followers, only: :index
  end
end

app/models/active.rb
class Active < ActiveHash::Base

  self.data = [
    {id: 0, name: '---'},
    {id: 1, name: '読書'}, 
    {id: 2, name: '筋トレ'}, 
    {id: 3, name: 'ランニング'}, 
    {id: 4, name: 'ウォーキング'}, 
    {id: 5, name: 'プログラミング'}, 
    {id: 6, name: '英会話'}, 
    {id: 7, name: '勉強'}, 
    {id: 8, name: '瞑想'}, 
    {id: 9, name: '掃除'}, 
    {id: 10, name: 'その他'}
]

  include ActiveHash::Associations
  has_many :cans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/can.rb
class Can < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :active
  belongs_to_active_hash :place
  belongs_to_active_hash :set_time

  with_options numericality: { other_than: 0 } do
    validates :active_id
    validates :place_id
    validates :set_time_id
  end

  validates :image, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy   #外部キーを持つデータのdestroyを行うための設定
  has_many :likes, dependent: :destroy
  has_one_attached :image

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :user
  belongs_to :can
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :can

  validates_uniqueness_of :can_id, scope: :user_id
end

app/models/place.rb
class Place < ActiveHash::Base

  self.data = [
    {id: 0, name: '---'},
    {id: 1, name: '自宅'}, 
    {id: 2, name: '公園'}, 
    {id: 3, name: 'ジム'}, 
    {id: 4, name: '職場'}, 
    {id: 5, name: '教室'}, 
    {id: 6, name: 'カフェ'}, 
    {id: 7, name: '図書館'}, 
    {id: 8, name: '屋外'}, 
    {id: 9, name: 'その他'} 
]

  include ActiveHash::Associations
  has_many :cans
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/set_time.rb
class SetTime < ActiveHash::Base

  self.data = [
    {id: 0, name: '---'},
    {id: 1, name: '15分'}, 
    {id: 2, name: '30分'}, 
    {id: 3, name: '45分'}, 
    {id: 4, name: '1時間00分'}, 
    {id: 5, name: '1時間15分'}, 
    {id: 6, name: '1時間30分'}, 
    {id: 7, name: '1時間45分'}, 
    {id: 8, name: '2時間00分'}, 
    {id: 9, name: '2時間15分'},
    {id: 10, name: '2時間30分'},
    {id: 11, name: '2時間45分'},
    {id: 12, name: '3時間00分'},
    {id: 13, name: '3時間以上'} 
]

  include ActiveHash::Associations
  has_many :cans
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cans, dependent: :destroy   #外部キーを持つデータのdestroyを行うための設定
  has_many :comments, dependent: :destroy   #外部キーを持つデータのdestroyを行うための設定
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user

  
  validates :nickname, presence: true, length: { maximum: 6 }

  def already_liked?(can)
    self.likes.exists?(can_id: can.id)
  end

  
end

app/controllers/cans_controller.rb
class CansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :set_search]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_search, only: [:index, :set_search]

  def index
    @cans = Can.all.order("created_at DESC")
  end

  def new
    @can = Can.new
  end

  def create
    @can = Can.new(can_params)
    if @can.valid?
      @can.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    # @can = Can.find(params[:id])
    @comment = Comment.new
    @comments = @can.comments.includes(:user)
  end

  def edit
    # @can = Can.find(params[:id])
  end

  def update
    # @can = Can.find(params[:id])
    @can.update(can_params)
    if @can.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    # @can = Can.find(params[:id])
    @can.destroy
    redirect_to root_path
  end

  def set_search
    @search = Can.ransack(params[:q])
    @cans = @search.result
  end

  private

  def set_item
    @can = Can.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && @current_user.id == @can.user_id
      redirect_to action: :index
    end
  end

  def can_params
    params.require(:can).permit(:active_id, :place_id, :set_time_id, :description, :image).merge(user_id: current_user.id)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(can_id: params[:can_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @can = Can.find(params[:can_id])
    @like = current_user.likes.find_by(can_id: @can.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @cans = @user.cans
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cans_helper.rb
module CansHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaruPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="header">
      <div class="header-left">
        <h1 class="header-title"><a href="/">Action Log</a></h1>
      </div>
      
        <% if user_signed_in? %>
          <div class="user_nav">
            <a><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a>
            <a><%= link_to "投稿する", new_can_path, class: "post" %></a>
          </div>
        <% else %>
          <div class="user_nav">
            <a><%= link_to "ログイン", new_user_session_path, class: "post" %> </a>
            <a><%= link_to "新規登録", new_user_registration_path, class: "post" %></a>
          </div>
        <% end %>
      </div>
    </div>

    </header>
    <%= yield %>
    <footer class="footer">

      <p class="copyright"> 
        Copyright Action Log 2021.
      </p>

    </footer>
  </body>
</html>

app/views/shared/_can.html.erb
<%# 投稿表示 %>
<div class="main-top">
  <% @cans.each do |can| %>
    <div class="can">
      <%= link_to image_tag(can.image, class: :can_img), can_path(can.id) if can.image.attached? %>
      <div class="can_name">
      <% if user_signed_in? %>
        <%= link_to "#{can.user.nickname}", user_path(can.user), class: :greeting_link %>さん
      <% else %>
        <%= can.user.nickname %>
      <% end %>

          <div class="can_active">
            -<%= can.active.name %>-
          </div>
      </div>
      <% if current_user %>
        <% if current_user.already_liked?(can) %>
          <%= link_to can_likes_path(can), method: :delete do %>
            <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to can_likes_path(can), method: :post do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
      <% end %>
      <%= can.likes.count %>
    </div>
  <% end %>
</div>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search.html.erb
<%# 検索表示 %>
<div class="search">
  <%= search_form_for @search, url: set_search_cans_path, class: :search_top do |f| %>
    <%= f.collection_select :active_id_eq, Active.all, :id, :name, class:"search-select" %>
    <%= f.submit '検索', class:"search-btn" %>
  <% end %>
</div>